pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                // Chạy file test_login.py của bạn trong thư mục a/tests/
                sh 'python -m unittest discover -s a/tests' 
            }
        }
    }
}
